version: "3.8"

services:
    webapp:
        build: .
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=db;Database=NoteKeeperPro;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
        depends_on:
            - db
        networks:
            - notekeeper-network

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=YourStrong!Passw0rd
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - notekeeper-network

networks:
    notekeeper-network:
        driver: bridge

volumes:
    sqldata:
